version: '2.1'

services:
  api:
    container_name: mutant-api
    build: '.'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '8000:8000'
    depends_on:
      db:
        condition: service_healthy
  db:
    container_name: mutant-db
    image: mysql:8
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: HRrUdp9f
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=HRrUdp9f --execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 30s
      retries: 15

