version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.18.3
      - image:  circleci/mysql:8
        environment:
          MYSQL_ROOT_PASSWORD: HRrUdp9f
          MYSQL_DATABASE: mutant_test
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run ESLint
          command: npm lint
      - run:
          name: Run test suite
          command: npm test
          environment:
            TYPEORM_HOST: localhost
            TYPEORM_USERNAME: root
            TYPEORM_PASSWORD: HRrUdp9f
